language: node_js
node_js:
  - 'lts/*'
cache: npm
install:
  - npm install
script: 
  - npm run lint
deploy:
  provider: script
  script: ./scripts/ci_deploy.sh
  skip_cleanup: true
  on:
    branch: master
